pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Policy Evaluation') {
            steps {
                nexusPolicyEvaluation iqApplication: extractProjectName(), iqStage: env.GIT_BRANCH == 'master' ? 'build': 'develop',
                    iqScanPatterns: [
                        [scanPattern: 'requirements.txt']
                    ]
            }
        }
    }
}

// This function extracts the project name from the GIT_URL environment variable.
def extractProjectName() {
    def match = env.GIT_URL =~ /.+\/([^\/]+)\.git/
    return match[0][1]
}
